version: "3.3"

networks:
  backend:

services:
  web-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python wsgi.py
    ports:
      - "5001:5001"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  db:
    driver: local

#volumes:
#  local_pgdata:
#  pgadmin-data: