"""empty message

Revision ID: 0158a7499c86
Revises: 460617519b83
Create Date: 2022-08-20 19:47:15.918903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0158a7499c86'
down_revision = '460617519b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('categ2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'categ2')
    # ### end Alembic commands ###
