"""empty message

Revision ID: 460617519b83
Revises: 3a15b643a63a
Create Date: 2022-08-20 19:09:35.754517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460617519b83'
down_revision = '3a15b643a63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('un_news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('un_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='un_news_pkey')
    )
    op.drop_table('bots')
    # ### end Alembic commands ###
