"""empty message

Revision ID: 4cb2272f2ab8
Revises: 0158a7499c86
Create Date: 2022-08-20 23:34:41.170271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb2272f2ab8'
down_revision = '0158a7499c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('login', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('password', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('steam_id', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('shared_secret', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('identity_secret', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('steam_api', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('tm_api', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('google_drive', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('proxy', sa.String(), nullable=True))
    op.drop_column('bots', 'category')
    op.drop_column('bots', 'categ2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('categ2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bots', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bots', 'proxy')
    op.drop_column('bots', 'google_drive')
    op.drop_column('bots', 'tm_api')
    op.drop_column('bots', 'steam_api')
    op.drop_column('bots', 'identity_secret')
    op.drop_column('bots', 'shared_secret')
    op.drop_column('bots', 'steam_id')
    op.drop_column('bots', 'password')
    op.drop_column('bots', 'login')
    op.drop_column('bots', 'comment')
    # ### end Alembic commands ###
